### ISSUE TITLE
The query time takes forever.

### ISSUE THREAD

**Issue by qian-feng** [seahorn/seahorn#145]
Hi, sorry to bother you again. I found that seahorn sometimes conducted the query forever even if the code itself is small enough. The sample i tried is as following:

#include "seahorn/seahorn.h"
extern int nd();
//#include <stdio.h>

int f1(int x){
	if(x>200) 
		return 1000;
	return -1;
}

int f2(int x){
	if(x>200)
		return 1000;
	return -2;
}

int test(void){
	int re=0;
	int n = 2000;
	re = 0;
	int x=0;
	int z=1;
	while(x<=n){
		if(z>x){ 
   		   x++;
		   re += f1(x); 
		}
		else{
		   z++;
		   re += f2(x);
		}
	}
	sassert(re>1000);
}

In the above example, although the loop is bounded, seahorn can still get stuck at fp.query() in HornSolver.cpp. Does it mean the solver cannot resolve the CHC clauses? I really appreciate your help!
Thanks very much!

**Comment by agurfinkel** [comment]
This seems to be a difficult example for seahorn. I've tried it with different bounds, and it still diverges. Can you parameterize the problem so that it can be tried with smaller bounds? 
What is the expected inductive invariant?

**Comment by qian-feng** [comment]
I simplified the above example as following, it seems that it can still not solve it. 
#include "seahorn/seahorn.h"
extern int nd();
//#include <stdio.h>

int main(void){
	int re=1000;
	int n = 1000;
	int x=0;
	int z=1;
	while(x<=n){
		if(z>x){ 
   		   x++;
		   re += 1000; 
		}
		else{
		   z++;
		   re += 1000;
		}
	}
	sassert(re>=1000);
}
However, if i set "n=1000" to "n=nd()", it can finished within 2s. I wonder why it happens. Does it mean  seahorn unroll loop for bounded loop? and let spacer or crab to solve the invariant for unbounded?

**Comment by agurfinkel** [comment]
SeaHorn unrolls loops and applies other optimizations up to a certain point and then send the result to spacer. If at this point some loops remain, their are solved by spacer by finding inductive invariants.
Since the verification problem is undecidable, spacer is based on various heuristics. One of its weaknesses are concrete loop bounds. Such loops are necessarily unrolled. Our usual work-around is to replace such loops by symbolic bounds. However, that heuristic fails to recognize your example :(

A workable solution is to replace `int n = 1000; ` with `int n = nd() ; assume(n == 1000); `. This hides the fact that `n` is `1000` from the LLVM optimizer, but still makes it available to spacer. This would be more accurate than simply replacing `n` with `nd()`. 

I also notice that in this example, default optimizations make the problem more complex -- that is, the inductive invariants are more complicated. Solving with `sea pf -O0` is faster and simpler than with `sea pf -O3`, which is the default. You can view the invariants using `--show-invars` flag.

btw: I'd be interested to know more about where your examples are from and what is an area/problem in which you are applying SeaHorn.

**Comment by qian-feng** [comment]
Hi Gurfinkel,

Thanks for your prompt response! The detailed explanation really helps a lot! I found this issue when testing that case. The above example is based on the example under ./play/test02.c. I am currently working on the loop summary generation, that is why I select and test seahorn. 

Thanks for your help!
