### ISSUE TITLE
Unexpected result on strlen

### ISSUE THREAD

**Issue by rdzhou** [seahorn/seahorn#150]
I am testing seahorn on libc functions (strlen in this case). I wonder why the result for the following program is "sat". Could you please give me some explanation? Thank you very much.
```c
#include <stdio.h>
#include <stdlib.h>
// #include <string.h>
#include <seahorn/seahorn.h>


int xstrlen(const char *s) {
	const char *t=s;
	while(*t++) {
	}
	return t - s - 1;
}

int main(int argc, char const *argv[])
{
    /* code */
    char s[] = "hello";
    // printf("xstrlen(s) == %d\n", xstrlen(s));
    sassert(xstrlen(s) == 5);
	return 0;
}
```

**Comment by caballa** [comment]
The string "hello" is a global variable in LLVM. 
The line `char s[] = "hello"` is translated to an `Alloca` instruction that allocates memory for `s` followed by a call to `memcpy` that copies the global variable into `s`. 

SeaHorn does not reason precisely about `memcpy` so that's the reason why the solver doesn't know that `s` contains the string `hello`. We have a pass that lower `memcpy` into a loop consisting of `Store` instructions for each element of the buffer. However, this pass does not always lower the `memcpy`.

**Comment by qian-feng** [comment]
Hi，if possible, could you tell me which pass you use for lower memory pass? Thanks

**Comment by caballa** [comment]
`lib/Transforms/Scalar/PromoteMemcpy.cc`
It should be easy to modify the pass for your purpose.
