### ISSUE TITLE
Termination checking failing in docker image

### ISSUE THREAD

**Issue by DominicPM** [seahorn/seahorn#156]
The termination analysis feature of SeaHorn seems to be broken in the docker image.

To reproduce (within docker):

    ./bin/sea term $FILE.c

produces a warning about a missing z3 module.  After

    pip install z3

another error is produced about,

    IOError: 'module' object has no attribute 'Fixedpoint'

This seems to happen with any C file, including the following which can be used to reproduce the issue:

    int main(int argc, char** argv) { return 0; }

**Comment by agurfinkel** [comment]
SeaHorn is using a custom version of `z3`, installing one from pip will not work.
I'm not sure why the version that is installed in docker is not picked up by the termination checker.
We have not worked on termination checker for a while, so something got stale...

**Comment by letonchanh** [comment]
Hi @DominicPM: Have you been able to run the termination checker of Seahorn? I am also trying to make it work and I have some updates regarding this issue. First, the pip version of the z3 prover is `z3-solver`, but as indicated by @agurfinkel, it didn't help because it doesn't support the parameter `pdr.utvpi`. I also tried another version of z3 at https://bitbucket.org/spacer/code/src/spacer/ but  I got a segmentation fault error. I am trying to find an older version of Seahorn (probably the commit d48cfe8a which is the last modification on Seahorn's termination analysis) in which the termination analysis works.

**Comment by agurfinkel** [comment]
`pdr.utvpi` is a parameter that has been removed. You should be able to simply remove it from the code without any adverse effect.

**Comment by letonchanh** [comment]
Now I am able to compile and run the termination analysis of Seahorn at the commit d48cfe8. If you would like to use, I have a docker image at `letonchanh/seahorn:d48cfe8` on Docker Hub. The command to run is e.g `/seahorn/build/run/bin/sea_svcomp --cex=error-witness.graphml -m64 --spec=/sv-benchmarks/c/termination-restricted-15/ALL.prp /sv-benchmarks/c/termination-restricted-15/c.01-no-inv_true-termination.c` where `sv-benchmarks` is the SV-COMP benchmarks, I tried the branch `svcomp16`.
