### ISSUE TITLE
[llvm-5.0] false positive with --enable-indvar

### ISSUE THREAD

**Issue by mchalupa** [seahorn/seahorn#192]
Hi,

if I run seahorn (nightly build, version `0.1.0-rc3-5bcd7c9`) on https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loop-lit/hhk2008.c and use `--enable-indvar`, seahorn answers sat. Without this option, seahorn answers unsat.

```
sea pf --horn-stats --enable-indvar hhk2008.c
[...] 
sat

************** BRUNCH STATS ***************** 
BRUNCH_STAT Result FALSE
BRUNCH_STAT Horn 0.00
BRUNCH_STAT HornClauseDB::loadZFixedPoint 0.00
BRUNCH_STAT HornifyModule 0.00
BRUNCH_STAT LargeHornifyFunction 0.00
BRUNCH_STAT seahorn_total 0.01
************** BRUNCH STATS END ***************** 
```

**Comment by agurfinkel** [comment]
Hey @mchalupa , thank you for reporting this. Quick explanation:
`--enable-indvar` causes bit-vector operation (`xor`) to be added to the IR.
Since bit-vector operations are over-approximated, a potential counterexample is produced.

You can see the code being analyzed using `--oll=OUT.ll` option.
You can validate whether the counterexample is bit-precise using `--cex=h.ll --horn-cex-bv`.

In your example, the validation fails, showing that bit-precise reasoning is required for this example.

**Comment by agurfinkel** [comment]
Should work as expected in a new nightly

**Comment by mchalupa** [comment]
@agurfinkel Thanks for the explanation!
