### ISSUE TITLE
Memory safety query

### ISSUE THREAD

**Issue by abhcs** [seahorn/seahorn#194]
I have 2 questions for you:

1. Do you have a memory model and instrumentation to check spatial memory safety for all pointer dereferences (not just pointers to arrays) in C code where there are no dynamic memory (de)allocations?

2. Do you have a memory model and instrumentation to check temporal memory safety for all pointer dereferences in C code where dynamic memory (de)allocations are present? For instance, say we want to verify that some inserts, deletes, and finds on a linked list satisfy temporal memory safety - have you seen success with seahorn on problems like this?

**Comment by caballa** [comment]
We don't have instrumentation for temporal memory safety and our memory model would need probably to be modified for that. 

We have only focused on spatial memory safety and we are still actively working on that, both on effective instrumentations of buffer overflows and improving the pointer analysis so that we can prove trivially as many accesses as possible. 

Take a look at our post http://seahorn.github.io/seahorn/memory%20safety/2017/05/27/seahorn-memory-safety.html

The command `sea abc --abc-dsa=sea-cs test.c` should add assertions to check that each nontrivial memory access is safe and then it will try to prove those assertions.
