### ISSUE TITLE
Seg fault when try to get live info from unreachable basic block

### ISSUE THREAD

**Issue by jorgenavas** [seahorn/seahorn#2]
This is an old error that I though we already solved.

These are the commands:

- ``` clang -c -emit-llvm  ntdrivers-simplified/cdaudio_simpl1_false-unreach-call_true-termination.cil.c  -o cdaudio_simpl1_false-unreach-call_true-termination.cil.bc```

- ```seapp cdaudio_simpl1_false-unreach-call_true-termination.cil.bc -horn-inline-all -o cdaudio_simpl1_false-unreach-call_true-termination.cil.pp.bc```

- ```seahorn cdaudio_simpl1_false-unreach-call_true-termination.cil.pp.bc -horn-solve -horn-step=large```

The error is:

```seahorn: ../lib/seahorn/LiveSymbols.cc:227: const ExprVector& seahorn::LiveSymbols::live(const llvm::BasicBlock*) const: Assertion `it != m_liveInfo.end ()' failed.```

It looks like that the pass that removes unreachable blocks (```RemoveUnreachableBlocksPass```) is indeed  never executed although in seahorn.cpp we call it several times.

I though that we needed to replace 
 ```void RemoveUnreachableBlocksPass::getAnalysisUsage (AnalysisUsage &AU) const {  }```
 
with 

```void RemoveUnreachableBlocksPass::getAnalysisUsage (AnalysisUsage &AU) const 
  { AU.setPreservesAll (); }```

but it doesn't help.

**Comment by agurfinkel** [comment]
I think `RemoveUnreachableBlocks` does run, but that is not the problem.

The underlying problem is that we do handle functions that have basic blocks that do not return. Inlining introduces calls to `verifier.error` into `main()`. These calls do not return, so they are followed by `unreachable` instruction. After merging exit nodes, `main()` has two exit nodes: one for normal return, and one for call to `verifier.error`.

The best solution is to apply mixed semantics `seapp --horn-mixed-sem` after inlining. This is the default behavior of `seahorn_inter.py` script.

This does not solve the problem for the inter-procedural no-mixed-semantics mode. If you need this urgently, let's talk. I have a few ideas that might work.
