### ISSUE TITLE
Can seahorn handle nondet value?

### ISSUE THREAD

**Issue by oraluben** [seahorn/seahorn#203]
I am using seahorn and have met a wired problem, here's a minimal repre:
```
int main() {
    int i = __VERIFIER_nondet_int();
    
    if (i == -1 && i*i > 9) __VERIFIER_error();
}
```
expected result: unsat
actual result: sat
command: both `sea pf test.c` and `sea bpf test.c` give the `sat` result
version: latest docker version

**Comment by caballa** [comment]
This is a well known limitation for the `pf` engine which tries to produce invariants. 
Since there is a non-linear constraint `i*i > 9`, the `pf` engine is imprecise. 

The `bpf` option alone only unrolls the program but it still uses the same imprecise semantics as `pf`, modeling precisely only linear operations. 

If you try `sea bpf --bmc=mono` then you should get `unsat`. The option `--bmc` performs bounded model checking using a **bitvector** precise semantics.

**Comment by agurfinkel** [comment]
Non-linear arithmetic is not well supported by arithmetic engines of SMT solvers. For that reason, SeaHorn over-approximates all non-linear operations. You can turn this off using `--horn-strictly-la=false` option. But this is unlikely to work except for special cases. Otherwise, using bit-precise semantics with bounded prover as suggested by @caballa
