### ISSUE TITLE
Check which assertions are failing

### ISSUE THREAD

**Issue by zunchenhuang** [seahorn/seahorn#217]
Dear seahorn researchers,

Is there a way to tell which assertion(s) are failing where a test has multiple assertions? Assume we use the default pf option. I notice there is only info about the unsat/sat and the stats but not telling which assertion(s) are failing.

Really appreciate it!

Best,
Phil

**Comment by caballa** [comment]
For cases where the result is `sat` (i.e., the solver found a counterexample) we try to generate an executable that follows the counterexample generated by the solver. The option is `sea exe-cex` rather than `sea pf`. You can see a demo here (http://seahorn.github.io/). Scroll down until you see a video. You can also take a look at our blog (http://seahorn.github.io/seahorn/cex/validation/2018/08/03/seahorn-cex-vstte18.html). 
A key advantage of having an executable is that you can run your favorite debugging tool (e.g., gdb or valgrind) to see exactly which assertion fails and why

**Comment by zunchenhuang** [comment]
@caballa Thanks a lot Jorge!
