### ISSUE TITLE
Symbolic input buffers

### ISSUE THREAD

**Issue by davidtr1037** [seahorn/seahorn#294]
What is the analogous nd() API for buffers/strings?
For example, how should I mark the buffer __name__ as unconstrained/symbolic?
```
char name[10];
if (atoi(name) == 7) {
  // ...
}
```

**Comment by agurfinkel** [comment]
There is nothing out of the box that supports unbounded symbolic regions. Mostly because reasoning with such regions would require quantified invariants, and they are not well supported. In many cases, though, this can be avoided or worked around in the encoding.

For example, you can memset a region to a nd() value, or rewrite the program (automatically) so that every load from the buffer is replaced by a call to nd().

**Comment by davidtr1037** [comment]
I used the __VERIFIER_nondet_char API for memset'ing a string/buffer, I guess that's should do the work, right?

**Comment by agurfinkel** [comment]
that is definitely a way.

**Comment by davidtr1037** [comment]
OK, thanks.
