### ISSUE TITLE
Reasoning about memory errors

### ISSUE THREAD

**Issue by davidtr1037** [seahorn/seahorn#295]
When I analyze the following program:
```
#include "seahorn/seahorn.h"
extern int nd();

int main(void) {
    unsigned int k = nd();
    __VERIFIER_assume(k > 10);

    char b[10] = {0,};
    b[k] = 100;
    __VERIFIER_error();
}
``` 
It reutrns __sat__, that is, the error at the last line is reachable.

In other execution models (symbolic/native), that's not always the case:
In KLEE, for example, this line is unreachable, since the out-of-bound error at the assignment:
```
b[k] = 100
```
will terminate the state before reaching the invocation of ____VERIFIER_error__.
In native execution, this line also might be unreachable, as the above assignment may lead to a crash. Probably not in this simple example, but that's not hard to construct one.

How seahorn handles out-of-bound memory accesses?
Is it able to report such errors?

**Comment by agurfinkel** [comment]
First of all, to understand what happens when a program contains undefined behavior, it is necessary to look at the bitcode that is given to seahorn and not the the original C code. For example, under default options, the program is optimized before it gets to seahorn, and at that point, undefined behavior might be exploited by the compiler in surprising way.

The answer to your actual question is unfortunately a bit complicated. SeaHorn hides many different engines and the engines come with different assumptions. If you are interested in undefined behavior than the new BMC engine is best suited for that. It attempts to model the program semantics with high level of fidelity (as, for example, you would expect from KLEE). It is however at early prototype stages. We would be happy to get you started on it, but would need to know about your use case to know how close it is to being useful for you.

The current default engine is CHC that attempts to discover program invariants. In that mode, it is assumed that the program has no undefined behavior. Generating invariants in presence of undefined behavior does not seem like a worthy (and definitely not an easy!) task. 

Furthermore, SeaHorn itself does not do any checks automatically (unlike KLEE or CBMC). It attempts to find a path to `__VERIFIER_error()` under assumption that there are no undefined behaviors **on that path**. This makes it possible to use SeaHorn for detecting undefined behavior, but it is up to the user to add assertions. For example, you can add an assertion `sassert(k <= 9)` before the assignment to `b[k]` and the assertion should be correctly shown to be violated. There are number of passes in seahorn (bound check, abc, smc) that attempt to synthesize such assertions automatically.  At the moment, these are experimental features that usually require tuning for particular use cases. 

Hope this helps.

**Comment by davidtr1037** [comment]
Thanks for the detailed response, that was indeed helpful:)
