### ISSUE TITLE
Unexpected SAT result

### ISSUE THREAD

**Issue by davidtr1037** [seahorn/seahorn#296]
I ran seahorn on the following example:
```
#include "seahorn/seahorn.h"
extern int nd();
extern char __VERIFIER_nondet_char();

int Atoi(char *str) {
    if (*str == '\0') {
       return 0;
    }

    int res = 0;
    int sign = 1;
    int i = 0;

    if (str[0] == '-') {
        sign = -1;
        i++;
    }

    for (; str[i] != '\0'; ++i) {
        if ( str[i] <= '0' || str[i] >= '9') {
            return 0;
        }
        res = res*10 + str[i] - '0';
    }
    return sign*res;
}

int main(void) {
    char str[2];
    str[0] = __VERIFIER_nondet_char();
    str[1] = __VERIFIER_nondet_char();
    assume(str[1] == 0);

    if (Atoi(str) == 100) {
        __VERIFIER_error();
    }
}
```
using the following command:
```
sea pf -g --cex=test.ll atoi.c
```
And the result was __sat__, which look wrong to me, since the length of __str__ is at most 1.
Do you know why that happens? Are there some specific flags that can fix that?

Not sure if it helps, but when the following block is removed:
```
if (str[0] == '-') {
    sign = -1;
    i++;
}
```
then the rersult is __unsat__, as expected.

**Comment by agurfinkel** [comment]
The source of the problem is non-linear multiplication. When a counter-example is produced, you can validate that it is bit-precise using `--bv-cex` option:
```
sea pf -g /tmp/ex2.c  --show-invars --cex=/tmp/h.ll --log=cex --bv-cex
```

This failed and produced a core containing the following atom:
```
(main@._crit_edge.i_0->(main@%_26_0=bvmul(main@%.01.lcssa.i_1, main@%.5.i_0)))
```

By default, seahorn abstracts non-linear arithmetic by non-determinism. 
Turning this off
```
sea pf -g /tmp/ex2.c  --show-invars --cex=/tmp/h.ll --log=cex --bv-cex --horn-strictly-la=false
```
interacts with some other parameters and the solver diverges.

Dumping the CHC file out of the solver and running through external solver works:

```
$ sea smt -g /tmp/ex2.c  --show-invars --cex=/tmp/h.ll --log=cex --bv-cex --horn-strictly-la=false -o out.smt2
$ z3 out.smt2
```

Current development branch `dev10` solves the instance correctly but with much simpler invariants.

You should not expect much when non-linear arithmetic is present. There is best effort support for it, but it is quite limited.

When debugging counterexamples, and all else fails, try `--log cex` option. We use it for debugging (so the support for users is minimal). It will output an overlay of instructions and SeaHorn interpretation. You have to spot where the interpretation is different from what you expect. 

Counterexample generation only supported when all functions are inlined (`--inline`). SeaHorn will work regardless, but without `--inline` the counterexamples might not be correct even when the result is correct (and correct for the right reason).
