### ISSUE TITLE
Handling strings

### ISSUE THREAD

**Issue by davidtr1037** [seahorn/seahorn#301]
I analyzed the following program:
```
#include "seahorn/seahorn.h" 
extern int nd();
extern char __VERIFIER_nondet_char();

int strcmp(register const char *s1, register const char *s2) {
    int r;
    while (((r = ((int)(*((unsigned char *)s1))) - *((unsigned char *)s2++)) == 0) && *s1++);
    return r;
}

int main(void) {
    char s[2];
    s[0] = __VERIFIER_nondet_char();
    s[1] = 0;

    if (strcmp(s, "1234") == 0) {
        __VERIFIER_error();
    }
    return 0;
}
```
using the following command:
```
sea pf -g --track=mem --cex=test.ll --dsa=sea-cs <file>
```
and the result was __sat__ (which is incorrect).

Do you know why that happens? Did I miss some flags?

**Comment by agurfinkel** [comment]
The CHC engine (that is the engine enabled by default) is very limited in its support for memory initialization (among other things). In particular, it treats all global initializers as non-deterministic and (and all global addresses as non-deterministic as well). In your example, the string literal "1234" is promoted to a global variable and is then lost to the analysis.

If you are after small but tricky examples in which precise memory reasoning is important, you should try our bmc engine instead. It works for this example since the loop is automatically unrolled to a sufficient depth. The command line options are:

```
sea bpf --bmc=mono --horn-bv2 /tmp/issue301.c  --log=opsem
```

An attempt is made to warn the user about anything that is not treated as the user might expect. This is still a work in progress which is likely to require quite a bit of tuning.

You may have better luck with it on `dev10` branch or `seahorn/seahorn-llvm10:nightly` docker since this is where the development for it is ongoing.

**Comment by davidtr1037** [comment]
The handling of global initializers is more like a technical issue or there is something more deep to that?
Could it be solved by adding a new array which is appropriately initialized?

Another related question:
I run a slightly different program with the command that you suggested and got  __unsat__:
```
#define N (10)
    
int strcmp(register const char *s1, register const char *s2) { 
    int r; 
    while (((r = ((int)(*((unsigned char *)s1))) - *((unsigned char *)s2++)) == 0) && *s1++);
    return r;
}
    
int main(void) {
    char s[N];
    for (int i = 0; i < N - 1; i++) {
        s[i] = __VERIFIER_nondet_char();
    }   
    s[N - 1] = 0;
    
    if (strcmp(s, "1234") == 0) {
        __VERIFIER_error();
    }
    return 0;
}
```
Here, N is 10 so it should be satisfiable.

**Comment by agurfinkel** [comment]
The loop is not unrolled sufficiently (or at all, actually) because it is deemed too complex. 

`sea bpf --hron-bv2 --bmc=mono --bound=5 -log=opsem issue301.c` gives sat

**Comment by agurfinkel** [comment]
to @agurfinkel : add to test cases for loop unrolling and loop peeling
