### ISSUE TITLE
Handling heap allocations

### ISSUE THREAD

**Issue by davidtr1037** [seahorn/seahorn#302]
I had some issue with the following program:
```
#include "seahorn/seahorn.h"
extern int nd();
extern char __VERIFIER_nondet_char();

#define OBJS (2)
#define N (32)

int main(void) {
    char *ptrs[OBJS];
    for (unsigned int i = 0; i < OBJS; i++) {
        char *obj = calloc(N, 1);
        obj[3] = 7 + i;
        ptrs[i] = obj;
    }

    unsigned k = nd();
    char *p = k == 0 ? ptrs[0] : ptrs[1];
    if (p[3] == 7) {
        __VERIFIER_error();
    }
}
```
which I ran using:
```
sea pf --track=mem --cex=test.ll --dsa=sea-cs <file>
```
and got the result __unsat__.

I looked in the generated smt2 query to understand why that happens:
- The write to the first object (in the loop) is done using some array A
- The write to the second object (in the loop) is done using some array B
- in the branch condition (p[3] == 7), array B is used and therefore the result is __unsat__.

Does it happen because if the dsa analysis?

By the way, if the initialization of the two objects is done without a loop:
```
char *a = calloc(N, 1);
char *b = calloc(N, 1);
a[3] = 7;
b[3] = 8;
```
Then the result is correct.

**Comment by agurfinkel** [comment]
dsa is definitely involved, but I'm not sure I follow the logic in the program. 

One suspect is `calloc`. From seahorn perspective, it is a function returning a non-deterministic values. Are you assuming that different calls to `calloc` return different values? If so, you need to specify this explicitly by providing a model of an allocator. 

There is more of this modeling in bmc engine (not sure about `calloc`, but we definitely support `alloca`). In CHC engine, there isn't much point of providing an exact model of an allocator out of the box because the engine will unlikely be able to solve results problems. Instead, we use CHC engine for cases where pointer analysis (dsa) is strong enough to rule out impossible aliasing and the property that we are trying to verify is true under all other forms of aliasing.

In particular, objects that alias analysis cannot separate (like objects from the same allocation site) are allowed to alias. Some of this can be refined by adding assumptions on the allocator. We usually do it directly in C. But one has to be careful so that assumptions are properly interpreted by LLVM and are not reduced too much.

**Comment by caballa** [comment]
The issue is related to how we model `calloc`. By default, we assume that the semantics of `calloc` creates a fresh SMT array where all elements are zero. This not always correct if we have to calls to `calloc` and then the returned pointer alias. This is exactly what is happening in your example. If you add the option `--horn-ignore-calloc` then we treat `calloc` as a function returning a non-deterministic value.

**Comment by davidtr1037** [comment]
Thanks for both answers.

So we I have two questions regarding that:
1.
Assuming that I want to model malloc/calloc/realloc as if it returns always a unique address (array),
how can I model that with SeaHorn? Do you have some example?
2.
What is the impact of DSA on the correctness of the results?
If DSA is not precise enough, then the SMT query is just getting more complicated or it might be actually incorrect?

**Comment by agurfinkel** [comment]
1. You need to develop an allocator. For example, keep a global variable that indicates how much memory is used  and return something bigger each time. There are two issues to be aware of:
   (a) you have to be very careful when converting between pointers and integers. There are 
         rules that C follows, and if you don't, the compiler will create a mess. 
         Here is one example I've done in the past with some model of an allocator: 
            https://github.com/seahorn/seahorn-tutorial/tree/master/mem
    (b) a custom allocator might confuse the alias analysis. Start on small examples. Look at 
          the graphs that sea-dsa produces. Make sure that all memory is ultimately allocated with
          malloc and assumptions are added for pointer addresses such that these assumptions
          are ignored by alias analysis. (see example above).
 `calloc` will be harder than others because you need to initialize unbounded memory.
I am worried about how the analysis will scale since with this model you need to cary complete
allocation info in the state. 

2. If DSA is sound, it's only effect is scalability. The current model that seahorn uses always results in an over-approximation. So UNSAT should be trusted. However, DSA makes number of assumptions that we find convenient but might be unsound for you. For example, there are somewhat unclear assumptions on how external functions are interpreted. But, for complete programs, DSA should be sound under the usual assumptions of C (modulo bugs, of course)

If I knew more about what you are trying to do with SeaHorn, I could give you a better advice on which direction to pursue. For example, we are working on a BMC engine (unrolling loops) and for that work we have multiple internal models of memory allocators that are suitable for different types of problems. This is what I usually use to validate examples similars to yours where memory management and things like alignment become crucial for verification.

**Comment by davidtr1037** [comment]
Currently, I don't have something specific that I would like to do.
I am a bit new in the area of model checking, so I am trying to get a basic feeling of how things work.
