### ISSUE TITLE
Interprocedural encoding incorrect with `--no-ms --no-reduce-main`

### ISSUE THREAD

**Issue by dbueno** [seahorn/seahorn#350]
**Describe the bug**
SeaHorn produces an incorrect encoding.

**To Reproduce**
1. Input file: [bad.ll.txt](https://github.com/seahorn/seahorn/files/5287615/bad.ll.txt)
2. `sea smt -o bad.smt2 -m64 --step=small --no-ms --no-reduce-main bad.ll`

This produces a SMT2 file which Z3 won't check (query isn't a no-arg relation), but with a trivial change it will: [bad.smt2.txt](https://github.com/seahorn/seahorn/files/5287618/bad.smt2.txt)

Z3 gives unsat but the input file has a counterexample: `main@entry -> 6 -> a@entry -> __VERIFIER_error`

**Expected behavior**
I expected the encoding to have a counterexample.

**Logs, Stacktraces, and Screenshots**
I understand that there are Numerous Frightening Warnings when I run `sea` above:
```
WARNING: Function a never returns.Inter-procedural analysis with such functions might not be supported.WARNING: found a call to verifier.error() in Function `a' at basic block _call                          
This should not happen. Perhaps a forgotten --devirt-functions option
Warning: the exit block of function a is unreachable 
```
So I understand if the fix is "don't compile with --no-ms --no-reduce-main". My question is why is inter-procedural analysis not supported in this case? I looked at the bitcode immediately before encoding and it didn't have any odd cases, such as undefined behavior.

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave 10.14.6
- SeaHorn: dev10 commit 18d75aab5736111085f08db99058de2a61e31941
 - LLVM: LLVM 10
 - Z3: z3-master

**Additional context**

**Comment by agurfinkel** [comment]
First of all, you are using an old flow that has not been maintained for a while. Some of the warnings are due to an expectation that this flow is not used.

Second, due to some technical reasons, SeaHorn does not support functions that do not (potentially) terminate. It expects every function to have a return location, even if that return location is unreachable. In your case, `verifier.error()` is not terminating and dominates all exit points of the function. A simple solution here is to wrap the call by a non-deterministic branch: `if (nd()) { __VERIFIER_error();}`

More principled solution would be to fix the requirement for having a return location. Either by changing the code to deal with this case, or automatically synthesizing an exit location that is potentially unreachable. 

To iterate, the requirement is that the CFG of a function has a unique exit point. It does not matter whether that exit point is actually reachable in the operational semantics.
