### ISSUE TITLE
Can the source code support newer version of llvm than 5.0?

### ISSUE THREAD

**Issue by Luweicai** [seahorn/seahorn#384]
It seems that the Readme (last modification was 17 months ago) fall behind the source code. （I know that the the latest one in docker hub can support the llvm 10.0.0). But I wonder whether source code could support newer verison than llvm 5.0. Had anybody do any test?

**Comment by McSinyx** [comment]
So does seahorse support newer LLVM?

**Comment by agurfinkel** [comment]
Our current development branch is `dev10` that supports LLVM10. We plan to transition to LLVM11 soon (the code should be close to being ready for that). Next to LLVM12. We usually stay with a version of LLVM for a while and then jump a few versions at once. 

Let me know what version of LLVM you would like SeaHorn to support.

**Comment by McSinyx** [comment]
I want to package SeaHorn downstream for NixOS, which currently has LLVM from 5 to 13.  Do you have a recommended branch?  If so, it'd be nice if there's a git tag (nixpkgs also allow unstable packages, but a released one is preferred).

**Comment by agurfinkel** [comment]
what is your timeline?

We are planning to make current `dev10` branch into `master`, and start new development branch for `llvm11+`. This, unfortunately, has been delayed due to other commitments. I can see if we can speed up our process. 

If you need this today, the only working branch is `dev10`. Everything else is either too old or too bleeding edge.

**Comment by McSinyx** [comment]
NixOS 21.11 shall be released shortly, so any SeaHorn version within the next six months would be good.  In the meantime I will try to package the `dev10` branch for a template.
