### ISSUE TITLE
Function Inlining for BMC

### ISSUE THREAD

**Issue by JakobKoempel** [seahorn/seahorn#497]
Hello,

for my bachelor thesis, I am using Seahorn's BMC to debug LLVM code generated from Structured Text. To get familiar with Seahorn, I first wrote a couple of LLVM programs by hand. Unfortunately, I don't seem to get correct results. For example:
```
%type = type {i1}

define void @main() {
entry:
	%0 = alloca %type
	call void @f(%type* %0)
	%1 = getelementptr %type, %type* %0, i32 0, i32 0
	%2 = load i1, i1* %1
	br i1 %2, label %bb1, label %bb2
bb1:
	call void @__VERIFIER_error()
	unreachable
bb2:
  ret void
}

define void @f(%type* %state){
entry:
	%0 = getelementptr %type, %type* %state, i32 0, i32 0
	store i1 false, i1* %0
	ret void
}

declare void @__VERIFIER_error()
```

When I run the following commands
```
seapp --horn-inline-all --horn-cut-loops -o tmp/safeCall.ll.pp.bc tests

seahorn --horn-solve --horn-sem-lvl=mem --horn-step=small --horn-sea-dsa=false --horn-bmc --time-passes -o smt/safeCall.ll.smt tmp/safeCall.ll.pp.bc
```

The resulting verdict is sat, which means that the call to __VERIFIER_error() is reachable (which it isn't). I already tried investigating the verdict by using the cex flag of the seahorn command but no counter example file is being generated. I think the problem has something to do with function calls and how they are inlined for BMC. Help would be appreciated. Thanks.

**Comment by agurfinkel** [comment]
You are using individual components instead of using the main script. This is not supported. An advanced user can do that, but we will not be able to provide much support.

Proper way to use seahorn is via the provided `sea` script. For your example, the following works for me:

```
sea bpf --bmc=opsem /tmp/issue497.ll
```

It is preferable to keep options in a yaml configuration file. The config file can be local, or on the web.
Here is an example of configuration that we often use

```
sea yama -y https://raw.githubusercontent.com/seahorn/verify-c-common/master/seahorn/sea_base.yaml bpf  /tmp/issue497.ll
```
You can download the `sea_base.yaml` file locally and modify it as necessary. 

You might also want to look at (or use parts of) our [verify-c-common](https://github.com/seahorn/verify-c-common) project for managing multiple verification tasks.
