### ISSUE TITLE
Counter-example does not violate the assertion

### ISSUE THREAD

**Issue by leonardoalt** [seahorn/seahorn#61]
Hi there,

I'm verifying the following code:
```
#include "seahorn/seahorn.h"

int nondet();

int square(int x)
{
    return x*x;
}

int main()
{
    int x = nondet();
    assume(x>1);
    assume(x<100);
    int y = square(x);
    sassert(y>0);
    return 0;
}
```
SeaHorn gives SAT for this assertion.
When I generate the counter-example, the error location is not executed.
Besides, when debugging, it says the values are x=2 and y=4, which shouldn't violate the assertion.

Any clues on what could be wrong here?

Cheers,
Leonardo

**Comment by caballa** [comment]
I think the problem is Z3 with non-linear constraints.


Jorge

**Comment by leonardoalt** [comment]
Hi Jorge,

thanks for the quick reply.
I also thought it was related to non-linear ops. But do you agree that it's inconsistent to have a SAT verification result with a witness that doesn't violate the assertion?

Leonardo

**Comment by caballa** [comment]
I wouldn't call it inconsistent but imprecise.

The problem is that the witness we produce cannot reach the error 
location which means that the solver says there is an error but we 
cannot prove that such an error exists.

This is actually the whole motivation of having executable witnesses 
because we cannot trust always the solver due to undecidability of 
non-linear constraints, too complex pointer constraints, etc.

So in this case, the result can be interpreted as inconclusive since the 
solver and the executable witness do not agree.

Jorge

**Comment by leonardoalt** [comment]
Oh I see, makes sense.
Thanks for the explanation!

Leonardo
