### ISSUE TITLE
warning: main function could not be found so program is trivially safe

### ISSUE THREAD

**Issue by Robbin1987** [seahorn/seahorn#65]
Hello all,

Created this issue to understand what is causing the warning mentioned in the title. I want to prove memory safety on an project of my own, same as the example that is used in the blog:

sea pf -O0 abc2.c --abc=global --show-invars

The only difference is, is that I execute each command seperately

I performed the following steps to get to the warning:

/* select .c file and create .bc */
/usr/bin/clang-3.6 -c -emit-llvm -D__SEAHORN__ -fgnu89-inline -m32 -Iinclude -o /tmp/main.bc ../../../../MBED_Source/Application/main.cpp

/* use .bc file and create pp */
/home/osboxes/Downloads/seahorn/build/run/bin/seapp -o /tmp/main.pp.bc --strip-extern=false --abc=global --abc-dsa-node=0 --abc-alloc-site=0 --kill-vaarg=true /tmp/main.bc

/* use pp and create ms */
/home/osboxes/Downloads/seahorn/build/run/bin/seapp -o /tmp/main.pp.ms.bc --horn-mixed-sem --ms-reduce-main /tmp/main.pp.bc

/* use ms and create .o */
/home/osboxes/Downloads/seahorn/build/run/bin/seaopt -f -funit-at-a-time -o /tmp/main.pp.ms.o.bc --enable-indvar=false --enable-loop-idiom=false --enable-nondet-init=false --unroll-threshold=150 --disable-loop-vectorization=true --disable-slp-vectorization=true --vectorize-slp-aggressive=false /tmp/main.pp.ms.bc

/home/osboxes/Downloads/seahorn/build/run/bin/seahorn --keep-shadows=true --horn-solve --horn-answer -horn-inter-proc -horn-sem-lvl=mem --horn-step=large /tmp/main.pp.ms.o.bc

If I understood it correctly then it not needed to apply additional code to prove the memory safety, because SeaHorn takes care of this. Is this correct?

Thanks for helping out!

Robbin

**Comment by caballa** [comment]
When that message is printed is because either the original program
did not have an assertion to prove or the front-end by itself
(`seapp`/`seaopt`) was able to prove that the assertion holds.

However, I don't understand how you get different results depending on
whether you run `sea pf` or each command individually. That should not
happen.

This is the program which is the one I believe you are trying to
prove. I call it `ex.c`:

    #include "seahorn/seahorn.h"
    #include <stdio.h>

    extern int nd();
    #define N 10
    int main(int argc, char**argv) {
      int i;
      int a[N];
      for (i = 0; i < N; i++)  {
        a[i] = i;
      }

     #ifndef ERROR
     printf("%d\n", a[i-1]);
     #else
     printf("%d\n", a[i]);
     #endif   
     return 0;
    }

If I type `sea pf -O0 --abc=global ex.c`

Then, I get `unsat`.

Then, I try each command separately:

- `clang -c -emit-llvm -D__SEAHORN__ -fgnu89-inline -m32 -I/Users/E30338/seahorn/include -o ./ex.bc ex.c`

- `seapp -o ./ex.pp.bc --strip-extern=false --abc=global --abc-dsa-node=0 --abc-alloc-site=0 --kill-vaarg=true ./ex.bc`

- `seapp -o ./ex.pp.ms.bc --horn-mixed-sem --ms-reduce-main ./ex.pp.bc`

- `seaopt -f -funit-at-a-time -o ./ex.pp.ms.o.bc --enable-indvar=false --enable-loop-idiom=false --enable-nondet-init=false --unroll-threshold=150 --disable-loop-vectorization=true --disable-slp-vectorization=true --vectorize-slp-aggressive=false ./ex.pp.ms.bc`

- `seahorn --keep-shadows=true --horn-solve -horn-inter-proc -horn-sem-lvl=mem --horn-step=large ./ex.pp.ms.o.bc`

I still get `unsat`.

Can you just run these five commands and tell me what you get?

They seem exactly the same ones you ran but just to double check. The
only thing you might need to change is the path to `seahorn/include`
in the first command.

**Comment by Robbin1987** [comment]
First of all, thanks for helping me out!

I tried to prove main.cpp, which is part of a bigger project. I left out all the required includes. 

But, in essence its similar to your example: it contains the 'int main(void)' function and other code to be executed.

**The output that I get is:**
WARNING: main function not found so program is trivially safe.
unsat

Maybe the unsat part here was very important to cover the fully story, sorry about that.

What confuses me (and that is really the question), is that it says "Main function not found so program is trivially safe". With that in mind I can understand that the program is unsat. It could mean: it is unsat, because I didn't couldn't check anything. Therefore I want to understand what this warning exactly means.

**Comment by caballa** [comment]
In the way we encode the verification conditions is that the program can be unsafe if main function returns.  If there is no main function then the program is considered trivially safe. This can happen because the original program didn't have a main function (e.g., you are trying to prove a library) or because the front-end realizes that the assertions are true and therefore it can optimize the program and get rid of the main function. The mixed-semantics pass can do that. 

If the original program does not have a main function but still you would like to verify it then we provide an option `--entry` to tell SeaHorn what other function will be the entry point of the program.

**Comment by Robbin1987** [comment]
to be clear: the main.cpp consist of a main function. Code snippet:

int main(void)
{
    /* General Configuration */
    Status_Init();
    USBSerial_Init();
    File_Init();
    Debug_Init();
    DMS_Init();
    Configuration_Init();
    LCDMenu_Init();
}

Currently is my understanding that for proving memory safety that I don't need to add assertions or other code and that SeaHorn handles this. Beside that could it be the case that since I only provided the main.cpp as source file and not the others that the main is optimized because of the external functions?

Is there a document that describes the possible options of SeaHorn? Is there also an option to give a specific function to be checked or could I use/misue the --entry option for that?

Thanks!

**Comment by caballa** [comment]
> Currently is my understanding that for proving memory safety that I don't need to add assertions 
> or other code and that SeaHorn handles this

Yes.

> Beside that could it be the case that since I only provided the main.cpp as source file and not the 
> others that the main is optimized because of the external functions?

Yes.

Where is defined the code of all functions (Status_init, etc) ? If the code is not available then there is nothing to verify! Actually, in that case you should get warnings from clang like this one:

      ex.c:4:1: warning: implicit declaration of function 'Status_Init' is invalid in C99 [-Wimplicit-function-declaration]
     Status_Init();

An the front-end will mark them as external.

**Comment by caballa** [comment]
> Is there a document that describes the possible options of SeaHorn? Is there also an option to 
> give a specific function to be checked or could I use/misue the --entry option for that?

Unfortunately, not.

But you can type the commands:

- `sea pp --help`: to display all preprocessor options
- `sea ms --help`: to display all mixed-semantics options
- `sea opt --help`: to display all optimizer options
- `sea horn --help`: to display all the middle-end (generator of verification conditions) options.

**Comment by Robbin1987** [comment]
Status_init() is located in a different source file. It was pretty dump and now I think that I understand why it gives me the warning that it cannot find the main function.

Should I generated by the CLang command the different .bc files and combine these or how should I process these different source files? Could it be llvm-link?

**Comment by Robbin1987** [comment]
Clang mentioned that it could not link multiple source files directly into a single .bc file. llvm-link seems to do the trick.

Currenlty the last step is running. lets see what will happen. For testing purpose I added a source file with the definition of Status_init() and in comparison with before the llvm DSA analysis output was mentioning more memory read/writes than before.

Thanks for your explaination!
