### ISSUE TITLE
False negative results for verification

### ISSUE THREAD

**Issue by ezudheen** [seahorn/seahorn#82]
Here I attach two programs from SVCOMP-16

[dtuc.c.log](https://github.com/seahorn/seahorn/files/1368123/dtuc.c.log)
[sqrt.c.log](https://github.com/seahorn/seahorn/files/1368125/sqrt.c.log)

The verification results by seahorn indicated the assertion fails (error state is reachable)
But actually the assertion is satisfiable and (error state is not reachable)

I have run the program using the following command
sea --crab --step=small --track=mem pf dtuc.c

Let me know how I can produce the correct verification result

**Comment by caballa** [comment]
For `sqrt` seahorn returns `sat` (meaning the error is reachable). I suspect that the reason is that the assertion contains a non-linear constraint (`sassert(su == ((a+1)*(a+1)));`) But I need to look deeper into the problem. 

For `dtuc` the problem seems different. With your command seahorn returns `sat` again. That command is running by default with `opt -O3`. For some reason the optimized code is the following:

```
define i32 @main() #1 {
.lr.ph.preheader:
  tail call void @seahorn.fn.enter() #2
  br label %.lr.ph

.lr.ph:                                           ; preds = %.lr.ph.preheader
  tail call void @seahorn.fail() #2
  br label %.lr.ph.split

.lr.ph.split:                                     ; preds = %.lr.ph
  ret i32 42
}
```
The formula that seahorn builds is such that it's sat if `ret` is reachable. With this optimized code `ret` is obviously reachable. 

However, if we disable the optimizations by adding `-O0` the results are:

```
sea pf -O0 dtuc.c --show-invars

unsat
Function: main
main@entry: true
main@_bb:
		(main@%k.0.i>=0)
	((main@%i.0.i<=0)||(main@%k.0.i>=1))
	((main@%k.0.i>=3)||(main@%i.0.i<=2))
	((main@%k.0.i>=2)||(main@%i.0.i<=1))
main@_bb2:
		((main@%j.0.i<=0)||(main@%k.1.i>=1))
	((main@%j.0.i<=2)||(main@%k.1.i>=3))
	(main@%j.0.i<=3)
	((main@%j.0.i<=1)||(main@%k.1.i>=2))
main@verifier.error.split: false
```
This inconsistency between `-O0` and `-O3` should not happen. 
Thank you for reporting it. I'll look into that.

**Comment by ezudheen** [comment]
Here I attach two more programs with false negative results. 

1. inc.c program increment x from 0 to 100

[inc.c.log](https://github.com/seahorn/seahorn/files/1378333/inc.c.log)

2. dec.c program decrement x from a value larger than 0 to 0

[dec.c.log](https://github.com/seahorn/seahorn/files/1378334/dec.c.log)

Can you identify the reasons?

**Comment by caballa** [comment]
I looked at inc.c.log and I think I found the reason for that program. I'll come back to you soon.

**Comment by caballa** [comment]
After looking at `inc.c` and `dtuc.c` some LLVM optimization (GVN) was removing one of the assumptions so that's why we were getting false positives with `-O3`. If you the add the option `--no-promote-assumptions` you should get the expected results in these two programs regardless of the level of optimization (`-O0` or -`O3`).

**Comment by ezudheen** [comment]
Hi, could you check the following program also.
[proCos_Que.c.log](https://github.com/seahorn/seahorn/files/1381724/proCos_Que.c.log)
